# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import task_pb2 as task__pb2


class TaskStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartTask = channel.stream_unary(
                '/Task/StartTask',
                request_serializer=task__pb2.StartingTask.SerializeToString,
                response_deserializer=task__pb2.StartingStatus.FromString,
                )
        self.QueryStatus = channel.unary_unary(
                '/Task/QueryStatus',
                request_serializer=task__pb2.RunningTask.SerializeToString,
                response_deserializer=task__pb2.RunningStatus.FromString,
                )
        self.GetResult = channel.unary_stream(
                '/Task/GetResult',
                request_serializer=task__pb2.CompletedTask.SerializeToString,
                response_deserializer=task__pb2.ResultFile.FromString,
                )


class TaskServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartTask(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartTask': grpc.stream_unary_rpc_method_handler(
                    servicer.StartTask,
                    request_deserializer=task__pb2.StartingTask.FromString,
                    response_serializer=task__pb2.StartingStatus.SerializeToString,
            ),
            'QueryStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryStatus,
                    request_deserializer=task__pb2.RunningTask.FromString,
                    response_serializer=task__pb2.RunningStatus.SerializeToString,
            ),
            'GetResult': grpc.unary_stream_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=task__pb2.CompletedTask.FromString,
                    response_serializer=task__pb2.ResultFile.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Task', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Task(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartTask(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/Task/StartTask',
            task__pb2.StartingTask.SerializeToString,
            task__pb2.StartingStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Task/QueryStatus',
            task__pb2.RunningTask.SerializeToString,
            task__pb2.RunningStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Task/GetResult',
            task__pb2.CompletedTask.SerializeToString,
            task__pb2.ResultFile.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
