# Generated by Django 4.2.2 on 2023-07-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_example', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='log_file_name',
        ),
        migrations.AddField(
            model_name='example',
            name='example_kind',
            field=models.CharField(default='netflow', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='example',
            name='example_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
