# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import example_pb2 as example__pb2


class RunExampleStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/RunExample/Start',
                request_serializer=example__pb2.StartingExample.SerializeToString,
                response_deserializer=example__pb2.StartingStatus.FromString,
                )
        self.QueryStatus = channel.unary_unary(
                '/RunExample/QueryStatus',
                request_serializer=example__pb2.RunningExample.SerializeToString,
                response_deserializer=example__pb2.RunningStatus.FromString,
                )


class RunExampleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RunExampleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=example__pb2.StartingExample.FromString,
                    response_serializer=example__pb2.StartingStatus.SerializeToString,
            ),
            'QueryStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryStatus,
                    request_deserializer=example__pb2.RunningExample.FromString,
                    response_serializer=example__pb2.RunningStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RunExample', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RunExample(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RunExample/Start',
            example__pb2.StartingExample.SerializeToString,
            example__pb2.StartingStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RunExample/QueryStatus',
            example__pb2.RunningExample.SerializeToString,
            example__pb2.RunningStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
