# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\"3\n\x07\x45xample\x12\x12\n\nexample_id\x18\x01 \x01(\x05\x12\x14\n\x0c\x65xample_name\x18\x02 \x01(\t\"C\n\x06Status\x12\x12\n\nexample_id\x18\x01 \x01(\x05\x12\x14\n\x0cis_completed\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t2N\n\nRunExample\x12\x1c\n\x05Start\x12\x08.Example\x1a\x07.Status\"\x00\x12\"\n\x0bQueryStatus\x12\x08.Example\x1a\x07.Status\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EXAMPLE']._serialized_start=17
  _globals['_EXAMPLE']._serialized_end=68
  _globals['_STATUS']._serialized_start=70
  _globals['_STATUS']._serialized_end=137
  _globals['_RUNEXAMPLE']._serialized_start=139
  _globals['_RUNEXAMPLE']._serialized_end=217
# @@protoc_insertion_point(module_scope)
